vim.opt.rtp:append(".")
vim.opt.rtp:append("~/.vim-plug/plenary.nvim")
vim.opt.rtp:append("~/.vim-plug/neotest")
vim.opt.rtp:append("~/.vim-plug/nvim-treesitter")
vim.opt.rtp:append("~/.vim-plug/nvim-nio")
vim.cmd.runtime({ "plugin/plenary.vim", bang = false })
vim.cmd.runtime({ "plugin/neotest.lua", bang = false })
vim.cmd.runtime({ "plugin/nvim-treesitter.lua", bang = false })
