describe("describe", function()
    context("context", function()
        it("it", function()
            assert.are.same(1, 1)
        end)
    end)

    insulate("insulate", function()
        spec("spec", function()
            assert.are.same(1, 1)
        end)
    end)

    expose("expose", function()
        test("test", function()
            assert.are.same(1, 1)
        end)
    end)
end)
