name: LuaRocks release

on:
  push:
    tags:
      - 'v*'
  pull_request: # Will test a local install without uploading to luarocks.org

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Lint
        uses: leafo/gh-actions-luarocks@v4.0.0
        run: luarocks lint neotest-busted-scm-1.rockspec
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test and upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
