name: style

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  style:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.16.1
          args: --check lua/ tests/
