name: tests

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  tests:
    name: run
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        neovim_version: ['v0.9.2', 'v0.10.0', 'nightly']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}
      - name: Install neovim plugins
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-neotest/neotest ~/.local/share/nvim/site/pack/vendor/start/neotest
          git clone --depth 1 https://github.com/nvim-neotest/nvim-nio ~/.local/share/nvim/site/pack/vendor/start/nvim-nio
          ln -s "$(pwd)" ~/.local/share/nvim/site/pack/vendor/start
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - name: Install busted
        run: |
          luarocks init
          luarocks config --scope project lua_version 5.1
          luarocks install busted 2.2.0
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Run tests
        run: ./tests/run_tests.sh
